export const TRAIN_DATE = '日期'
export const ORIGIN_STATION = '出發站'
export const DESTINATION_STATION = '到達站'
export const DEFAULT_SELECT_OPTION = '請選擇'
export const NO_SELECT_STATION = '請選擇站別'
export const NOT_BE_THE_SAME_STATION = '出發與到達站必須不同'

export const TRAIN_NUMBER = '車次'
export const DEPATURE_TIME = '出發時間'
export const ARRIVAL_TIME = '抵達時間'
export const TRIVAL_TIME = '行車時間'
export const AVAILABLE_SEAT = '剩餘車廂'
export const FARE = '票價'

export const STANDARD_SEAT = '標準車廂'
export const BUSINESS_SEAT = '商務車廂'